name: pusatani
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  buttons_tabbar: ^1.3.6
  carousel_indicator: ^1.0.6
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  custom_line_indicator_bottom_navbar: ^0.0.8
  dio: ^4.0.6
  dotted_border: ^2.0.0+3
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.1
  get: ^4.6.5
  google_fonts: ^3.0.1
  image_picker: ^0.8.6
  localstorage: ^4.0.0+1
  lottie: ^2.0.0
  shimmer: ^2.0.0
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
