name: SPusatani app release

on:
  push:
    tags:
      - '*'
#    branches: [ master ]
jobs:
  version:
    name: Fetching Repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch all history for all tags and branches
        run: |
          git fetch --prune --tags

  build:
    name: Build APK and Create release
    needs: [ version ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.4'
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
          architecture: x64
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk -v --target-platform android-arm,android-arm64
      - run: flutter build appbundle -v --target-platform android-arm,android-arm64
      - name: Create a Release in Github
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/app-release.aab"
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ steps.version.outputs.content }}
          commit: ${{ github.sha }}
      - name: Upload appbundle to Github Release
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab

#  release:
#    name: Release app to Internal track
#    needs: [ build ]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Get appbundle from artifact
#        uses: actions/artifact@v3
#        with:
#          name: appbundle
#      - name: Release app to internal track
#        uses: r0adkll/upload-google-play@v1
#        with:
#          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
#          packageName: com.diskominfotik.smart_asn
#          releaseFile: app-release.aab
#          track: internal
#          whatsNewDirectory: distribution/whatsnew
